name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm lint

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Typecheck
        run: pnpm typecheck

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: pnpm test

  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Lint GitHub Actions workflows
        uses: reviewdog/action-actionlint@e0207a28405ecad11953ba625a95d92f7889572a # v1
        with:
          fail_on_error: "true"
